apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: blog-app

spec:

  replicas: 2

  strategy:
    type: RollingUpdate

    rollingUpdate:

      maxUnavailable: 0
      maxSurge: 1

  selector:

    matchLabels:
      app: backend

  template:

    metadata:

      labels:
        app: backend

    spec:

      containers:

      - name: backend

        image: pratik0712/backend-service:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5003

        env:

        - name: PORT
          value: "5003"

        - name: DB_HOST
          value: mysql-service

        - name: DB_PORT
          value: "3306"

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD

        resources:

          requests:
            cpu: "200m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet:

            path: /health
            port: 5003
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2

        livenessProbe:
          httpGet:
            path: /health
            port: 5003

          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 2