apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: blog-app

type: Opaque

stringData:

  MYSQL_ROOT_PASSWORD: root123

  MYSQL_DATABASE: blog_db

  MYSQL_USER: Admin

  MYSQL_PASSWORD: Admin123